data_file_name: "./data/Node Information Rows Removed.xlsx"
ml_flow_endpoint: 'http://127.0.0.1:8080'

hyper_parameters:
  learning_rate: 0.005
  epochs: 100
  batch_size: 8
  weight_decay: 0.05

training_details:
  train_split: 0.8
  feature_columns : [
        'Source Local','source_traffic_count','Summed Centrality',
        'Access Point Local Centrality Scores',
       'Access Point Collector Centrality Scores',
       'Access Point Minor Arterial Centrality Scores',
       'Access Point Other Centrality Scores',
       'Access Point Major Arterial Centrality Scores',
       'Source Collector', 'Source Minor Arterial', 'Source Other',
       'Source Major Arterial', 'Source speed', 'Target Local',
       'Target Collector', 'Target Minor Arterial', 'Target Other',
       'Target Major Arterial', 'Target speed','Total Path Distance',
       'Access Points Local', 'Access Points Collector',
       'Access Points Minor Arterial', 'Access Points Other',
       'Access Points Major Arterial','Path Local', 'Path Collector',
       'Path Minor Arterial', 'Path Other', 'Path Major Arterial', 'Legs Diff'
    ]
  target_column: "target_traffic_count"